Ju/ednx/LC-V2:
eduNEXT/edunext-platform pull request #416
Opened 2020-09-25 15:24 UTC by mariajgrimaldi

**Description**

This feature does a match between the languages that the user accepts -on their browser- and the languages available on this tenant. Ednxsite awareness for language selection. It replaces the regular DarkLang app with a ednxsite aware configuration.

**Tests**

Following the Feature Document, added LANGUAGE_CODE and released_languages to a test microsite:

```
"LANGUAGE_CODE":"en",
"released_languages":"en,ru,fr,es-419,de-DE,pt-BR"
```

**Tests results**

LMS:

![Screenshot from 2020-09-25 10-59-39](https://user-images.githubusercontent.com/64440265/94282892-5ea20680-ff1e-11ea-87e9-5b0b898ce71b.png)

STUDIO:

![Screenshot from 2020-09-25 11-10-17](https://user-images.githubusercontent.com/64440265/94284279-23083c00-ff20-11ea-9b53-324609e27749.png)

**Is there a best way of doing this?**

I thought about moving this feature to eox-tenant or another plugging where it could make sense, it would be something like:

* Inherit from `DarkLangMiddleware` and override process_request as is done in this PR. Then, place this new middleware in the same spot as DarkLangMiddleware
* Make a proxy model using `DarkLangConfig` and override `released_languages_list` as is done in this PR

I wanted to start a discussion about if this change is worth it or not before trying it.

2020-09-28 16:26 UTC, andrey-canon requested changes

2020-09-28 16:26 UTC, andrey-canon commented on openedx/core/djangoapps/dark_lang/middleware.py
> +        ednx_locale = settings.FEATURES.get("EDNX_SITE_AWARE_LOCALE", False)
This could be the first line and use ednx_locale in the line  90

2020-09-28 16:26 UTC, andrey-canon commented on openedx/core/djangoapps/dark_lang/middleware.py
> +                return
```suggestion
        if not settings.FEATURES.get("EDNX_SITE_AWARE_LOCALE", False) and not DarkLangConfig.current().enabled:
            return
```

2020-09-28 16:26 UTC, andrey-canon commented on openedx/core/djangoapps/dark_lang/models.py
> +            return site_released_langs
```suggestion
        released_languages = self.released_languages

        if settings.FEATURES.get("EDNX_SITE_AWARE_LOCALE", False):
            site_released_langs = getattr(settings, "released_languages", None)            
            released_languages = site_released_langs if site_released_langs else  []
```

and change the line 57 to `languages = [lang.lower().strip() for lang in released_languages.split(',')]`

Thoughts ??

2020-09-30 14:08 UTC, mariajgrimaldi commented on openedx/core/djangoapps/dark_lang/models.py
> +            return site_released_langs
good idea, I'll try it

2020-09-30 15:31 UTC, mariajgrimaldi commented on openedx/core/djangoapps/dark_lang/models.py
> +            return site_released_langs
I did this:
```
        released_languages = self.released_languages

        if settings.FEATURES.get("EDNX_SITE_AWARE_LOCALE", False):

            site_released_langs = getattr(settings, "released_languages", None)
            released_languages = site_released_langs if site_released_langs else ""

        languages = [lang.lower().strip() for lang in released_languages.split(',')]

        # Put in alphabetical order
        languages.sort()

        return languages
```
I changed `else []` for `else ""` so the `.split()` won't fail

2020-09-30 15:34 UTC, mariajgrimaldi commented on openedx/core/djangoapps/dark_lang/models.py
> +            return site_released_langs
For what I tested, the behavior is the same, when `site_released_langs` is `None` this happens in both cases:

![Screenshot from 2020-09-30 11-32-15](https://user-images.githubusercontent.com/64440265/94706840-b2db2b00-0310-11eb-9063-e6143a9eef05.png)
So I guess the change is OK

2020-09-30 15:39 UTC, mariajgrimaldi commented on openedx/core/djangoapps/dark_lang/middleware.py
> +        ednx_locale = settings.FEATURES.get("EDNX_SITE_AWARE_LOCALE", False)
using `self.ednx_locale`?

2020-09-30 15:41 UTC, andrey-canon requested changes

2020-09-30 15:41 UTC, andrey-canon commented on openedx/core/djangoapps/dark_lang/models.py
> +
unnecessary space

2020-09-30 15:41 UTC, andrey-canon commented on openedx/core/djangoapps/dark_lang/models.py
> +        languages = [lang.lower().strip() for lang in released_languages.split(',')]
remove the blank space after this in order to do the diff smaller

2020-09-30 15:41 UTC, andrey-canon commented on openedx/core/djangoapps/dark_lang/middleware.py
> +        ednx_locale = settings.FEATURES.get("EDNX_SITE_AWARE_LOCALE", False)
@mariajgrimaldi

2020-09-30 16:49 UTC, mariajgrimaldi commented on openedx/core/djangoapps/dark_lang/middleware.py
> +        ednx_locale = settings.FEATURES.get("EDNX_SITE_AWARE_LOCALE", False)
what do we gain doing that? it will be used just once in process_request

2020-10-01 17:59 UTC, andrey-canon commented on openedx/core/djangoapps/dark_lang/middleware.py
> +        ednx_locale = settings.FEATURES.get("EDNX_SITE_AWARE_LOCALE", False)
yes, you are right github doesn't show the whole file and I thought it was  in the same method

2020-10-02 19:03 UTC, merged