[ju/ednx/LD-9] Remove preview and get urls from configuration_helpers
eduNEXT/edunext-platform pull request #417
Opened 2020-09-25 18:27 UTC by andrey-canon

## Description
LD-9 requires eox-tenant in order to override SiteConfigurations

2020-09-28 20:21 UTC, felipemontoya requested changes

2020-09-28 20:21 UTC, felipemontoya commented on common/djangoapps/util/course.py
> +            'SITE_NAME',
If we are moving to use LMS_BASE instead of SITE_NAME, we should already do that here

2020-09-28 20:21 UTC, felipemontoya commented on common/djangoapps/util/course.py
> +            'SITE_NAME',
Actually, we can move all this into looking for LMS_ROOT_URL which already has all everything including the `https://` bit

2020-09-30 22:32 UTC, andrey-canon commented on common/djangoapps/util/course.py
> +            'SITE_NAME',
@felipemontoya  done

2020-10-02 15:30 UTC, mariajgrimaldi approved these changes

2020-10-02 22:46 UTC, merged