Updating authentication file with bearer authentication
eduNEXT/edunext-platform pull request #422
Opened 2020-09-29 16:56 UTC by vad33r

Add support to django-oauth2-provider and django-oauth-toolkit

2020-09-29 17:18 UTC, andrey-canon requested changes

2020-09-29 17:18 UTC, andrey-canon commented on openedx/core/lib/api/authentication.py
> +    allow_inactive_users = True
the last empty line is missing, Why do you include this line? where `allow_inactive_users` is used ?

2020-09-29 17:18 UTC, andrey-canon commented on package-lock.json
> +      "integrity": "sha1-+PLIh60Qv2f2NPAFtph/7TF5qsg="
This file must not be included in this pr

2020-09-29 18:47 UTC, mariajgrimaldi commented on openedx/core/lib/api/authentication.py
> +    allow_inactive_users = True
is this class used?

2020-09-30 20:02 UTC, felipemontoya approved these changes
Lets fix the test and write the migration path document somewhere, but I'll leave the approval already

2020-10-01 20:32 UTC, merged