ju/ednx/BC-19 Add eox-core and create dependencies folder structure
eduNEXT/edunext-platform pull request #430
Opened 2020-10-02 22:51 UTC by andrey-canon

## Description
This add the dependencies' structure for edunext requirements and includes the first dependency(eox-core)

2020-10-02 22:55 UTC, morenol commented on requirements/edunext/base.in
> +-c ../constraints.txt
@andrey-canon 

What do you think about something like 

```-c ../edx/base.txt```

So we don't have to add the constraints for those packages?

2020-10-02 23:12 UTC, felipemontoya requested changes
I like the overall aproach. I would still like to add the comments on why we are using what we are using.

If this is well documented, do you think we still would find the dashboard table with the dependencies useful?

2020-10-02 23:12 UTC, felipemontoya commented on requirements/edunext/base.in
> +# 1. When adding a new dependency, add a comment to the end of the line
If we are doing this, please do this on eox-core ;)

2020-10-04 16:01 UTC, morenol commented on requirements/edunext/base.in
> +eox-core                            # Edunext core modifications. This plugin is necessary since this contains the most of edunext custom changes and the edunext logic businesses[required by saas].
In master, we are using eox-core[sentry,tpa].
Will that change be part of a future PR? or should we add that in this PR?

2020-10-05 23:20 UTC, andrey-canon commented on requirements/edunext/base.in
> +eox-core                            # Edunext core modifications. This plugin is necessary since this contains the most of edunext custom changes and the edunext logic businesses[required by saas].
done

2020-10-05 23:46 UTC, morenol approved these changes

2020-10-06 14:12 UTC, merged