[WIP] ju/ednx/JD-1: Microsite aware key-secret pairs for oauth
eduNEXT/edunext-platform pull request #433
Opened 2020-10-08 18:54 UTC by mariajgrimaldi

**Description**

This PR allows each microsite to have its own key-secret pair. 

In previous migrations, the function `get_setting` was also changed so we could get the key/secret from the microsite settings. To be able to reduce the number of components that JD-1 involves, I decided to look for the key/secret JUST in the OauthProviderConfig.

So this PR removes the searches of key/secret from:
- Microsite settings
- From the MICROSITE_SECRETS variable

**Tests**
I've tested this in my local environment using Google and it seems to work.

**What to take into consideration:**

- If we want to store the client secrets in the database, maybe it should be a good idea to encrypt them. 
- This change means that we need to do a data-migration to organize the data in the production environment. This data-migration will move the key/secrets from MICROSITE_SECRETS and Microsites settings to OautnProviderConfig.

2020-10-08 20:55 UTC, felipemontoya requested changes
I would like to understand the consequences of the key change as well as the data changes that we would need to do in the PROD data for this to work with the current clients

2020-10-08 20:55 UTC, felipemontoya commented on common/djangoapps/third_party_auth/__init__.py
> +        # This forces the module to be enabled on a per microsite basis
```suggestion
        # This forces the module to be enabled on a per tenant basis
```

2020-10-08 20:55 UTC, felipemontoya commented on common/djangoapps/third_party_auth/models.py
> +    KEY_FIELDS = ('slug',)
I like this idea, but don't quite understand the implications.

Does this change the URL that acts as the entry point for the auth process?

2020-10-08 20:55 UTC, felipemontoya commented on common/djangoapps/third_party_auth/models.py
> +            return super(OAuth2ProviderConfig, cls).current(provider_slug)
Is this super().current method the one that fetches all the models and iterates through them?

2020-10-08 20:55 UTC, felipemontoya commented on common/djangoapps/third_party_auth/models.py
> +            return super(OAuth2ProviderConfig, cls).current(provider_slug)
It might already be time to refactor that so that it does not run a for on top of all models

2020-10-08 21:55 UTC, mariajgrimaldi commented on common/djangoapps/third_party_auth/models.py
> +    KEY_FIELDS = ('slug',)
I changed this from `backend_name` to `slug` because when we do this: 

https://github.com/eduNEXT/edunext-platform/blob/e86c68ad861328b04497b6457e81adbbcbd5ca92/common/djangoapps/third_party_auth/models.py#L399

The method `current` (from super) will look for the ProviderConfig using the slug field:
https://github.com/edx/django-config-models/blob/8ef133d808ff7f3efed325e74c85804b39b1436c/config_models/models.py#L139

and this filter:
https://github.com/edx/django-config-models/blob/8ef133d808ff7f3efed325e74c85804b39b1436c/config_models/models.py#L141

will be: `filter(slug=provider_slug)`

If I didn't do that, the filter would be: `filter(backend_name=provider_slug)` and then `current` would return a temporary object (not the real config)

In fact, `KEY_FIELDS = ('slug',)`  is the default as stated in: https://github.com/eduNEXT/edunext-platform/blob/e86c68ad861328b04497b6457e81adbbcbd5ca92/common/djangoapps/third_party_auth/models.py#L92

edX changed it to backend_name here:
https://github.com/edx/edx-platform/pull/20070

2020-10-08 22:25 UTC, mariajgrimaldi commented on common/djangoapps/third_party_auth/models.py
> +    KEY_FIELDS = ('slug',)
how do I check whether

> Does this change the URL that acts as the entry point for the auth process?

if it does not even work? 

For example, when I started testing with Google the button didn't even appear.

2020-10-08 22:33 UTC, mariajgrimaldi commented on common/djangoapps/third_party_auth/models.py
> +            return super(OAuth2ProviderConfig, cls).current(provider_slug)
For what I've searched this is the current method:
https://github.com/edx/django-config-models/blob/8ef133d808ff7f3efed325e74c85804b39b1436c/config_models/models.py#L128

Do you mean this line?
https://github.com/edx/django-config-models/blob/8ef133d808ff7f3efed325e74c85804b39b1436c/config_models/models.py#L141

2020-10-20 17:52 UTC, andrey-canon commented on common/djangoapps/third_party_auth/__init__.py
> +        settings.FEATURES.get("ENABLE_THIRD_PARTY_AUTH_FOR_TEST", False)
why is this necessary, there is a consequence if this returns None instead of False ?

2020-10-20 17:52 UTC, andrey-canon commented on common/djangoapps/third_party_auth/identityserver3.py
> +        from django.contrib.sites.models import Site
why are you importing this inside the method ??

2020-10-20 17:52 UTC, andrey-canon commented on common/djangoapps/third_party_auth/identityserver3.py
> +        from openedx.core.djangoapps.theming.helpers import get_current_request
have you tried with `get_current_site` https://github.com/eduNEXT/edunext-platform/blob/ednx/juniper%2Bedunext/openedx/core/djangoapps/theming/helpers.py#L155

2020-10-20 17:52 UTC, andrey-canon commented on common/djangoapps/third_party_auth/strategy.py
> +            site_id = Site.objects.get_current(get_current_request()).id
same comment as above

2020-10-20 17:52 UTC, andrey-canon commented on openedx/core/djangoapps/auth_exchange/tests/test_forms.py
> +@unittest.skipIf(os.environ.get("CIRCLECI") == 'true', "Skip this test in Circle CI.")
why skip ?:(

2020-10-20 18:35 UTC, mariajgrimaldi commented on openedx/core/djangoapps/auth_exchange/tests/test_forms.py
> +@unittest.skipIf(os.environ.get("CIRCLECI") == 'true', "Skip this test in Circle CI.")
These tests pass locally but fail on CIRCLE CI.  I couldn't find an explanation, here the CIRCLE CI output: 
https://circleci.com/api/v1.1/project/github/eduNEXT/edunext-platform/7614/output/107/0?file=true&allocation-id=5f8eda49ee5df3231c3e5a90-0-build%2F5C7447E4

2020-10-21 19:31 UTC, mariajgrimaldi commented on common/djangoapps/third_party_auth/__init__.py
> +        settings.FEATURES.get("ENABLE_THIRD_PARTY_AUTH_FOR_TEST", False)
I cherry-picked this from ir/ednx/JD-1. I'm gonna do some tests to check if there's a difference

2020-10-21 22:56 UTC, mariajgrimaldi commented on common/djangoapps/third_party_auth/identityserver3.py
> +        from openedx.core.djangoapps.theming.helpers import get_current_request
the problem is that if there's no request, then the method returns None instead of a default

2020-10-21 23:11 UTC, mariajgrimaldi commented on common/djangoapps/third_party_auth/__init__.py
> +        settings.FEATURES.get("ENABLE_THIRD_PARTY_AUTH_FOR_TEST", False)
do you know why is this change? I can't figure it out. @felipemontoya

2020-10-28 17:31 UTC, andrey-canon approved these changes

2020-10-29 19:15 UTC, mariajgrimaldi commented
do you agree to merge this? @felipemontoya

2020-11-03 15:24 UTC, felipemontoya requested changes
Maybe I missed something or we already tried and something was not working, but in this particular point I think we should consider again modifying the `.current` method.

2020-11-03 15:24 UTC, felipemontoya commented on common/djangoapps/third_party_auth/__init__.py
> +        settings.FEATURES.get("ENABLE_THIRD_PARTY_AUTH_FOR_TEST", False)
I remember something about this needing to be turned on when the server starts (aka the yml file) and then be turned off for all the tenants which dont have a need for it.

2020-11-03 15:24 UTC, felipemontoya commented on common/djangoapps/third_party_auth/identityserver3.py
> +        return OAuth2ProviderConfig.current(site_id, "identityServer3")
In my mind it makes more sense to add the `site_id = Site.objects.get_current(get_current_request()).id` line inside the `.current` method of the `OAuth2ProviderConfig` class. This way we don't have to alter the signature of the function all over the codebase.

2020-11-03 15:24 UTC, felipemontoya commented on common/djangoapps/third_party_auth/models.py
> +        Unique string key identifying this provider. Must be URL and css class friendly.
If this must be URL and css class friendly, this means we must make it lowercase and remove spaces and maybe other chars. Then urlencode it. Why don't we force this to happen in this method?

2020-11-03 15:24 UTC, felipemontoya commented on common/djangoapps/third_party_auth/provider.py
> +        site_id = Site.objects.get_current(get_current_request()).id
All this edits would go away if we did the `current` mod

2020-11-04 14:21 UTC, mariajgrimaldi commented on common/djangoapps/third_party_auth/identityserver3.py
> +        return OAuth2ProviderConfig.current(site_id, "identityServer3")
OK, I made this change and for what I tested it seems to work.

2020-11-04 16:56 UTC, mariajgrimaldi commented on common/djangoapps/third_party_auth/models.py
> +        Unique string key identifying this provider. Must be URL and css class friendly.
I don't see why this is necessary, given that the provider_id format is: `oa2-site_id-backend_name`. Where `site_1` is a number and `backend_name` is one of these: ['dummy', 'google-oauth2', 'linkedin-oauth2', 'facebook', 'azuread-oauth2', 'identityServer3']
It's already URL and CSS friendly, isn't it?

Unless we assume that backend_name can be any string.

2020-11-10 03:07 UTC, felipemontoya approved these changes

2020-11-12 17:28 UTC, merged