ju/ednx/JU-1: Fix custom registration
eduNEXT/edunext-platform pull request #458
Opened 2020-11-20 18:23 UTC by mariajgrimaldi

This PR adds the ability to customize the registration form using settings.

For example:

If we want to add the field `Pet name` we would have to do the following:

1. Create a definition dictionary for our custom field:
```
        {
            "errorMessages": {
                "required": "Add your pet name."
            },
            "instruction": "Your pet name",
            "label": "Pet name",
            "name": "pet_name",
            "required": true,
            "restrictions": {
                "max_length": 10,
                "min_length": 3
            },
            "type": "text"
        }
```
2. Add that dictionary to `EDNX_CUSTOM_REGISTRATION_FIELDS`
3. Add `name` to `extended_profile_fields`
4. Add `name` to `REGISTRATION_EXTRA_FIELDS` with the value `optional` or `required`
```
    "REGISTRATION_EXTRA_FIELDS": {
        "city": "hidden",
        "confirm_email": "hidden",
        "country": "hidden",
        "gender": "optional",
        "goals": "optional",
        "honor_code": "required",
        "level_of_education": "optional",
        "mailing_address": "optional",
        "pet_name": "required",
        "specialty": "required",
        "terms_of_service": "hidden",
        "year_of_birth": "optional"
    }
```
5. Optional: if you want to specify: `REGISTRATION_FIELD_ORDER`

2020-11-20 18:50 UTC, andrey-canon requested changes

2020-11-20 18:50 UTC, andrey-canon commented on openedx/core/djangoapps/user_api/accounts/settings_views.py
> +            field_labels[field_name] = _(field.get("label"))
if `field.get("label") `returns `None`, does it work or raise an exception ?

2020-11-20 18:50 UTC, andrey-canon commented on openedx/core/djangoapps/user_api/accounts/settings_views.py
> +
unnecessary space

2020-11-20 18:50 UTC, andrey-canon commented on openedx/core/djangoapps/user_api/accounts/settings_views.py
> +        field_name = field.get("name")
missing empty line after this

2020-11-20 18:50 UTC, andrey-canon commented on openedx/core/djangoapps/user_api/accounts/settings_views.py
> +        options = field.get("options")
missing empty line after this

2020-11-20 18:50 UTC, andrey-canon commented on openedx/core/djangoapps/user_api/accounts/settings_views.py
> +    extended_profile_field_options = configuration_helpers.get_value('EXTRA_FIELD_OPTIONS', []) or custom_options
```suggestion
    extended_profile_field_options = configuration_helpers.get_value('EXTRA_FIELD_OPTIONS', custom_options) 
```
????

2020-11-20 18:50 UTC, andrey-canon commented on openedx/core/djangoapps/user_api/accounts/settings_views.py
> +
unnecessary space

2020-11-20 18:50 UTC, andrey-canon commented on openedx/core/djangoapps/user_authn/views/registration_form.py
> +            include_default_option=True if custom_field_dict.get("default") else False,
```suggestion
            include_default_option=bool(custom_field_dict.get("default")),
```

2020-11-20 18:50 UTC, andrey-canon commented on openedx/core/djangoapps/user_authn/views/registration_form.py
> +            field_options = extra_field_options.get(field_name) or custom_options
```suggestion
            field_options = extra_field_options.get(field_name, custom_options)
```

2020-11-25 16:30 UTC, felipemontoya approved these changes

2020-11-30 15:14 UTC, andrey-canon approved these changes

2020-11-30 15:17 UTC, merged