Add extended profile fields to the jwt payload.
eduNEXT/edunext-platform pull request #479
Opened 2020-12-30 23:35 UTC by andrey-canon

## Description
Add extended profile fields to the jwt payload in order to share any custom field data in the jwt response.

2021-01-04 13:16 UTC, mariajgrimaldi requested changes
I checked CMS tests and found this
```
payload = {'aud': 'video_pipeline_client_id', 'email': 'robot+test+639@edx.org', 'email_verified': True, 'exp': 1609373083, ...}
user = <User: cms_video_pipeline_service_user>

    def _attach_profile_claim(payload, user):
        """Add the profile claim details to the JWT payload."""
        try:
            # Some users (e.g., service users) may not have user profiles.
            profile = UserProfile.objects.get(user=user)
            name = profile.name
            fields = configuration_helpers.get_value('extended_profile_fields', [])
    
            if fields:
                extended_profile_fields = {key: value for key, value in json.loads(profile.meta).items() if key in fields}
    
        except UserProfile.DoesNotExist:
            name = None
            extended_profile_fields = None
    
        payload.update({
            'name': name,
            'family_name': user.last_name,
            'given_name': user.first_name,
            'administrator': user.is_staff,
            'superuser': user.is_superuser,
>           'extended_profile_fields': extended_profile_fields,
        })
E       UnboundLocalError: local variable 'extended_profile_fields' referenced before assignment

openedx/core/djangoapps/oauth_dispatch/jwt.py:200: UnboundLocalError
```

2021-01-05 14:13 UTC, mariajgrimaldi approved these changes

2021-01-06 20:34 UTC, felipemontoya requested changes

2021-01-06 20:34 UTC, felipemontoya commented on openedx/core/djangoapps/oauth_dispatch/jwt.py
> +        name = profile.name
Can we have a switch to turn this on or off?

I'm worried that this might be too heavy for the JWT and we have no way to turn it off on the fly.

Question, is this necessary only for some sites? if so, should we leave the switch be Off by default?

By switch I mean setting that we can alter from the tenant.

2021-01-06 20:52 UTC, andrey-canon commented on openedx/core/djangoapps/oauth_dispatch/jwt.py
> +        if fields and configuration_helpers.get_value('JWT_EXTENDED_PROFILE', False):
@felipemontoya  done in this line

2021-01-06 21:35 UTC, felipemontoya approved these changes

2021-01-07 22:47 UTC, merged