Li/ednx/li-7
eduNEXT/edunext-platform pull request #596
Opened 2021-12-09 21:55 UTC by MaferMazu

This PR allows token to be validated per site.

- [Jira](https://edunext.atlassian.net/browse/PS2021-1186?atlOrigin=eyJpIjoiZmYzYTNiOWZkNzA3NDQ4MjlmMzI3MGQ1YmM4NzZiYzYiLCJwIjoiaiJ9)
- [Documentation](https://docs.google.com/document/d/11mpYNDDLeLgXheiafrL-7aCbvdzooeVGhWF78_NesPU/edit#)

## How to test

2021-12-15 21:04 UTC, black-redoc requested changes
I

2021-12-15 21:04 UTC, black-redoc commented on openedx/core/lib/api/tests/test_authentication.py
> +            name='hogwarts-example',
```suggestion
            name='client-example',
```

2021-12-15 21:04 UTC, black-redoc commented on openedx/core/lib/api/tests/test_authentication.py
> +            token='hogwarts-dot-access-token',
```suggestion
            token='client-dot-access-token',
```

2021-12-15 21:23 UTC, MaferMazu commented on openedx/core/lib/api/tests/test_authentication.py
> +            name='hogwarts-example',
I think there would be no problem in leaving it as is, also several edunext-platform tests make references to hogwarts.
https://github.com/eduNEXT/edunext-platform/blob/master/openedx/core/djangoapps/credit/tests/test_views.py#L287
https://github.com/eduNEXT/edunext-platform/blob/master/openedx/core/djangoapps/credit/tests/test_api.py#L64
https://github.com/eduNEXT/edunext-platform/blob/master/openedx/core/djangoapps/enrollments/tests/test_views.py#L725

We have hogwarts in 18 files 🙈

2021-12-15 21:34 UTC, mariajgrimaldi commented on openedx/core/lib/api/tests/test_authentication.py
> -class OAuthDenyDisabledUsers(OAuth2AllowInActiveUsersTests):  # pylint: disable=test-inherits-tests
why are we removing this test?

2021-12-15 21:47 UTC, MaferMazu commented on openedx/core/lib/api/tests/test_authentication.py
> -class OAuthDenyDisabledUsers(OAuth2AllowInActiveUsersTests):  # pylint: disable=test-inherits-tests
I really don't know, but in master (juniper) we don't have it https://github.com/eduNEXT/edunext-platform/blob/master/openedx/core/lib/api/tests/test_authentication.py#L224, I'm going to take a look to see if there is a particular reason.

2021-12-15 22:13 UTC, MaferMazu commented on openedx/core/lib/api/tests/test_authentication.py
> -class OAuthDenyDisabledUsers(OAuth2AllowInActiveUsersTests):  # pylint: disable=test-inherits-tests
I think I did a wrong merge, I'm going to review, thanks for being on the lookout

2021-12-15 22:23 UTC, MaferMazu commented on openedx/core/lib/api/tests/test_authentication.py
> -class OAuthDenyDisabledUsers(OAuth2AllowInActiveUsersTests):  # pylint: disable=test-inherits-tests
Yes, I did a wrong merge, thanks 🔥

2021-12-15 22:55 UTC, black-redoc approved these changes

2021-12-16 17:55 UTC, MoisesGSalas requested changes

2021-12-16 17:55 UTC, MoisesGSalas commented on openedx/core/lib/api/authentication.py
> +from rest_framework.exceptions import AuthenticationFailed
I'm pretty sure you are only using `get_current_request` and `settings` as new imports. No need to touch the other ones.

2021-12-16 21:40 UTC, MoisesGSalas commented on openedx/core/lib/api/authentication.py
> +from rest_framework.exceptions import AuthenticationFailed
Reorder them as they were before (lilac.master). Keep the changes to the minimum so it's easier to read.

2021-12-16 22:36 UTC, MoisesGSalas commented on openedx/core/djangoapps/oauth_dispatch/tests/test_views.py
> +            client_id='dot-app-client-id-{grant_type}',
what happened whit this f-string?

2021-12-16 22:36 UTC, MoisesGSalas commented on lms/envs/production.py
> -MAX_BLOCKS_PER_CONTENT_LIBRARY = ENV_TOKENS.get('MAX_BLOCKS_PER_CONTENT_LIBRARY', MAX_BLOCKS_PER_CONTENT_LIBRARY)
Why remove this?

2021-12-17 13:42 UTC, MoisesGSalas approved these changes

2021-12-17 17:38 UTC, johanv26 approved these changes
I have tested it in my Limonero environment and it works.
![image](https://user-images.githubusercontent.com/51926076/146585118-8eec2147-a3c8-435d-96bf-aaa77a5d0146.png)
```
(venv) johanv@johan:~ $ curl --location --request POST 'http://tenant-validation.lms.limonero.edunext.link:8000/oauth2/access_token' \
> --header 'Cookie: openedx-language-preference=en' \
> --form 'client_id="tenant-validation"' \
> --form 'client_secret="tenant-validation-secret"' \
> --form 'grant_type="client_credentials"'
{"access_token": "yAQs0MhZzGqNoLgVa5euJ2KjaDiKF0", "expires_in": 31557600, "token_type": "Bearer", "scope": "read write email profile"}(venv) johanv@johan:~ $ 
(venv) johanv@johan:~ $ curl --location --request GET 'http://tenant-validation.lms.limonero.edunext.link:8000/eox-tagging/api/v1/tags/' \
> --header 'Authorization: Bearer yAQs0MhZzGqNoLgVa5euJ2KjaDiKF0'
{"count":0,"next":null,"previous":null,"results":[]}(venv) johanv@johan:~ $ 
(venv) johanv@johan:~ $ curl --location --request GET 'http://tenant-a.lms.limonero.edunext.link:8000/eox-tagging/api/v1/tags/' \
> --header 'Authorization: Bearer yAQs0MhZzGqNoLgVa5euJ2KjaDiKF0'
{"error_code":"token_nonexistent","developer_message":"The provided access token does not match any valid tokens."}(venv) johanv@johan:~ $ 
(venv) johanv@johan:~ $ 
```

2021-12-21 15:37 UTC, merged