translations: downloaded lilac translations
eduNEXT/edunext-platform pull request #614
Opened 2022-01-12 16:01 UTC by black-redoc

**description:**
Updated translations and downloaded from transifex.

**changes:**
updated i18n and static files from:
- lms/static
- cms/static
updated locales from:
- conf/locale

2022-01-12 18:23 UTC, mariajgrimaldi commented on .tx/config
> +
is this necessary?

2022-01-12 21:14 UTC, MoisesGSalas commented on .tx/config
> +
No, this file should stay the same.

2022-01-12 21:16 UTC, MoisesGSalas requested changes
There is a lot of files missing. Filtering by `*.po` extension only throws 2 files: `conf/locale/th/LC_MESSAGES/django.po` and `conf/locale/th/LC_MESSAGES/djangojs.po`

2022-01-14 14:46 UTC, black-redoc commented
> There is a lot of files missing. Filtering by `*.po` extension only throws 2 files: `conf/locale/th/LC_MESSAGES/django.po` and `conf/locale/th/LC_MESSAGES/djangojs.po`

What do you mean?

2022-01-17 15:17 UTC, mariajgrimaldi approved these changes

2022-01-17 15:32 UTC, merged