ci: add distro nightly tag to github workflows
eduNEXT/edunext-platform pull request #635
Opened 2022-04-14 19:39 UTC by Alec4r

## Description
This commit is a proposal to create each day one tag with the changes of the day.

This may be the first part of the CI that will build a new image for each nightly tag.

## How it works
This has a cronjob that will run daily at 04:00 (UTC) or 23:00 (Colombia TIme), then, this will check if there are new commits in a range of 23 hours if there aren't this won't create a tag.

### Tag format
```
vL.N20200414d2d0a67
 | |   |    |___ Last commit's hash (d2d0a67)
 | |   |___ Current date (2020-04-14)
 | |___ N: Nightly tag
 |___ eduNEXT distro release
```

2022-04-14 19:41 UTC, Alec4r commented
It was tested on a personal fork: https://github.com/Alec4r/edunext-platform/runs/6029454880?check_suite_focus=true

2022-04-19 01:00 UTC, felipemontoya commented
Would this tag the release every night? or only when there are changes?

2022-04-19 01:06 UTC, felipemontoya commented
I think this does exactly what is advertised.

Can you make it so, that the tag is `nightly/vL.N20200414d2d0a67` so that on most GUI clients, all the nightly tags can be collapsed as if they were in a directory?

Do you think we would like to have more than one nightly tag? for example, one for every open-release we currently support?
Or maybe I got it wrong and this is only for master and we will use it mostly for testing the integration with plugins and whatnot.

Anyways if you want to have this merged, go ahead, I'm good.

2022-04-19 01:07 UTC, felipemontoya requested changes
Just to mention again the tag in a `nightly/` namespace,

2022-04-19 01:25 UTC, Alec4r commented
> I think this does exactly what is advertised.
> 
> Can you make it so, that the tag is `nightly/vL.N20200414d2d0a67` so that on most GUI clients, all the nightly tags can be collapsed as if they were in a directory?
> 
> Do you think we would like to have more than one nightly tag? for example, one for every open-release we currently support? Or maybe I got it wrong and this is only for master and we will use it mostly for testing the integration with plugins and whatnot.
> 
> Anyways if you want to have this merged, go ahead, I'm good.

1. Yes, I will change the tag.
2.  We can have more than one, but for that, we must set each one in the action, or maybe we can use GitHub environment variables.
3. We may begin just with the master branch, It's enough for me.

2022-04-19 01:58 UTC, felipemontoya approved these changes

2022-04-20 20:48 UTC, MoisesGSalas approved these changes
I'm fine doing it like this, but I wonder if it wouldn't be better to simply retag de newest commit each day and have only one single nightly tag.

2024-04-01 20:19 UTC, MaferMazu commented
I talked with @Alec4r, who told me that this is not on our radar and that we can reopen it if necessary. I will close this.

2024-04-01 20:19 UTC, closed without merging