feat: create a new setting USE_DISCUSSIONS_MFE_FRONTEND
eduNEXT/edunext-platform pull request #809
Opened 2024-02-27 14:17 UTC by luisfelipec95

## Description

This PR adds a new setting `USE_DISCUSSIONS_MFE_FRONTEND` that will allow Discussions MFE to be enabled or disabled in the tenant

## Supporting information

[JIRA Issue DS-806](https://edunext.atlassian.net/browse/DS-806)

2024-02-29 22:32 UTC, dcoa commented on openedx/core/djangoapps/discussions/utils.py
> +        org, "USE_DISCUSSIONS_MFE_FRONTEND", False
Can we shorten it to `USE_DISCUSSION_MFE`?

2024-03-05 21:10 UTC, bra-i-am requested changes
Additionally, before approving the PR, I would like to see the changes in amberes first because, according to my experience, there may be different settings that can change the way the code is executed, and it would be great to ensure the proper functioning

2024-03-05 21:10 UTC, bra-i-am commented on openedx/core/djangoapps/discussions/utils.py
> +        org, "USE_DISCUSSIONS_MFE_FRONTEND", ENABLE_MFE_FOR_TESTING or False
I agree with the Dianis suggestion:

```suggestion
        org, "USE_DISCUSSIONS_MFE", ENABLE_MFE_FOR_TESTING or False
```

2024-03-05 21:10 UTC, bra-i-am commented on lms/djangoapps/discussion/tests/test_views.py
> +    features_with_enable_mfe_settings['ENABLE_MFE_FOR_TESTING'] = True
Maybe turning this variable a little bit more descriptive:

```suggestion
    FEATURES_WITH_DISCUSSION_MFE_ENABLED = settings.FEATURES.copy()
    FEATURES_WITH_DISCUSSION_MFE_ENABLED['ENABLE_MFE_FOR_TESTING'] = True
```

2024-03-05 22:11 UTC, luisfelipec95 commented on openedx/core/djangoapps/discussions/utils.py
> +        org, "USE_DISCUSSIONS_MFE_FRONTEND", False
sure, thanks

2024-03-06 13:53 UTC, bra-i-am commented
I've been testing the MFE in the amberes environment (I just updated the argo branch) and I don't know if it is even a problem, but when the flag is turned from `true` to `false`, the MFE lasts some minutes being disabled; despite the time it takes, everything works as expected.

**I would only like to ask for a last change**; I think it's better to follow the already established convention for the flag that we can find in the already existing flags in amberes (I need to apply the change in my PR too) so, instead of `USE_DISCUSSIONS_MFE` it should be called `ENABLE_DISCUSSION_MICROFRONTEND`, but before please let me know if you believe this change makes sense to you 

![image](https://github.com/eduNEXT/edunext-platform/assets/86393372/55428120-e3b1-42b1-a217-375e0e814287)

2024-03-06 13:59 UTC, bra-i-am approved these changes
I've been testing the MFE in the amberes environment and I don't know if it is even a problem, but when the flag is turned from `true` to `false`, the MFE lasts some minutes being disabled; despite the time it takes, everything works as expected.

2024-03-07 13:41 UTC, MaferMazu approved these changes
This looks good to me. I only have one suggestion: change the variable name USE_DISCUSSIONS_MFE_FRONTEND in the PR name or when you squash the commit because it is not consistent with the code.
Remember to add the documentation about how to enable or disable this here: https://docs.google.com/document/d/1j_kyDTdDaS1jnXgK0zbJOdz1XJja5lXvBzye8dmUhYA/edit?usp=sharing

2024-03-07 14:46 UTC, merged

2024-03-07 14:48 UTC, luisfelipec95 commented
> This looks good to me. I only have one suggestion: change the variable name USE_DISCUSSIONS_MFE_FRONTEND in the PR name or when you squash the commit because it is not consistent with the code. Remember to add the documentation about how to enable or disable this here: https://docs.google.com/document/d/1j_kyDTdDaS1jnXgK0zbJOdz1XJja5lXvBzye8dmUhYA/edit?usp=sharing

Thanks!!